export const MOCK_PRODUCTS = [
  {
    id: "1",
    name: "Jar Goat x 3gr",
    category: "Flores",
    family: "Premium",
    price: 150000,
    imageUrl: "/indor.png",
    categoryId: "1",
    isAvailable: true,
    thc: 24,
    cbd: 1,
    weight: 3,
    description: "Excelente variedad para relajación profunda y creatividad.",
  },
  {
    id: "2",
    name: "Gelato",
    category: "Flores",
    family: "Premium",
    price: 60000,
    imageUrl: "/Flower-Gelato.png",
    categoryId: "1",
    isAvailable: true,
    thc: 22,
    cbd: 2,
    weight: 1,
    description: "Aroma cítrico, efecto creativo y energía mental. Cultivada orgánicamente en la región antioqueña.",
  },
  {
    id: "3",
    name: "Passion",
    category: "Flores",
    family: "Premium",
    price: 10000,
    imageUrl: "/pasion.png",
    categoryId: "1",
    isAvailable: true,
    thc: 18,
    cbd: 1,
    weight: 1,
    description: "Perfecta para iniciar el día con buena vibra.",
  },
  {
    id: "4",
    name: "Conos x10",
    category: "Accesorios",
    family: "Básicos",
    price: 150000,
    imageUrl: "/06_category_accesorios.png",
    categoryId: "5",
    isAvailable: true,
    thc: 0,
    cbd: 0,
    weight: 10,
    description: "Conos pre-enrolados de la mejor calidad.",
  },
  {
    id: "5",
    name: "Armados x10",
    category: "Pre-rolls",
    family: "Conveniente",
    price: 100000,
    imageUrl: "/03_category_prerolls.png",
    categoryId: "2",
    isAvailable: true,
    thc: 20,
    cbd: 1,
    weight: 10,
    description: "Listos para disfrutar en cualquier momento.",
  },
  {
    id: "6",
    name: "Pre Roll",
    category: "Pre-rolls",
    family: "Conveniente",
    price: 100000,
    imageUrl: "/03_category_prerolls.png",
    categoryId: "2",
    isAvailable: true,
    thc: 19,
    cbd: 1,
    weight: 1,
    description: "Pre roll individual para probar.",
  },
  {
    id: "7",
    name: "Gomas x5 THC",
    category: "Otros",
    family: "Edibles",
    price: 70000,
    imageUrl: "/09_cookies.png",
    categoryId: "6",
    isAvailable: true,
    thc: 15,
    cbd: 5,
    weight: 5,
    description: "Gomitas relajantes con dosis precisa.",
  },
];
